[package]
name = "recrm-core"
version = "0.1.0"
authors = ["Ciffelia <mc.prince.0203@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.8"
parking_lot = "0.11.1"
num_cpus = "1.13.0"
log = "0.4.14"
